name: Build & Push

on:
  push:
    branches: [main]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }}

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Get current Git sha1
        id: commit
        run: echo "::set-output name=version::$(git rev-parse --short HEAD)"

      - name: Build and Push 🚀
        run: bash ./build.sh
        env:
          SHA: ${{ steps.commit.outputs.version }}
